### PR TITLE
T/107: A test util for checking multi assertions for different browsers

### LINKED ISSUE #107: Create a test util for checking few assertions for different browsers
Some of the tests fail because a selection on different browsers behave unpredictable but it is still correct.

For example – https://github.com/ckeditor/ckeditor5-link/issues/158#issuecomment-342729084 – this test fail on Edge because a selection is at the end of a element and inside it. Edge expects that the end of the selection will be after the element.

We could have the util which checks whether specified assertions are correct. If one of them will pass, the test is marked as passed. If all assertions will fail, the test is marked as fail and all errors will be logged. 

```js
it( 'test', () => {
	// Tests details...

	const assertEdge = () => {
	    expect( getData( doc ) ).to.equal(
	        '<$text bold="true" linkHref="url">f</$text>[<$text bold="true">ooba]<$text linkHref="url">r</$text></$text>'
	    );
	};

	const assertAll = () => {
	    expect( getData( doc ) ).to.equal(
	        '<$text bold="true" linkHref="url">f</$text>[<$text bold="true">ooba</$text>]<$text bold="true" linkHref="url">r</$text>'
	    );
	};

	checkAssertions( assertEdge, assertAll );
) );
```

### LINKED ISSUE #2927: Create a test util for checking few assertions for different browsers
Some of the tests fail because a selection on different browsers behave unpredictable but it is still correct.

For example – https://github.com/ckeditor/ckeditor5-link/issues/158#issuecomment-342729084 – this test fail on Edge because a selection is at the end of a element and inside it. Edge expects that the end of the selection will be after the element.

We could have the util which checks whether specified assertions are correct. If one of them will pass, the test is marked as passed. If all assertions will fail, the test is marked as fail and all errors will be logged. 

```js
it( 'test', () => {
	// Tests details...

	const assertEdge = () => {
	    expect( getData( doc ) ).to.equal(
	        '<$text bold="true" linkHref="url">f</$text>[<$text bold="true">ooba]<$text linkHref="url">r</$text></$text>'
	    );
	};

	const assertAll = () => {
	    expect( getData( doc ) ).to.equal(
	        '<$text bold="true" linkHref="url">f</$text>[<$text bold="true">ooba</$text>]<$text bold="true" linkHref="url">r</$text>'
	    );
	};

	checkAssertions( assertEdge, assertAll );
) );
```

### PR DESCRIPTION
**Pull request by pomek**
### Suggested merge commit message ([convention](https://github.com/ckeditor/ckeditor5-design/wiki/Git-commit-message-convention))

Tests: Added a new util which executes specified assertions. Closes ckeditor/ckeditor5#2927.

### CODE REVIEW

**Comment by szymonkups** [comment]
I'm not quite sure about the name: `checkAssertions` but cannot figure out anything better 😄

File: tests/_utils/utils.js [hunk 1]
```diff
@@ -31,6 +31,48 @@ const utils = {
...
+	 *          };
+	 *
+	 *          const assertAll = () => {
+	 *              // expect();
+	 *          };
+	 *
+	 *          testUtils.checkAssertions( assertEdge, assertAll );
+	 *      } );
+	 *
+	 * @param {Array.<Function>} assertions Functions that will be executed.
```
Comment (szymonkups) [inline tests/_utils/utils.js]: Not an array with functions. It should be documented as `{...Function}`.

File: tests/_utils-tests/utils.js [hunk 2]
```diff
@@ -0,0 +1,48 @@
...
+ * @license Copyright (c) 2003-2017, CKSource - Frederico Knabben. All rights reserved.
+ * For licensing, see LICENSE.md.
+ */
+
+import testUtils from '../_utils/utils';
+
+testUtils.createSinonSandbox();
+
+describe( 'utils', () => {
+	describe( 'checkAssertions', () => {
```
Comment (ma2ciek) [inline tests/_utils-tests/utils.js]: `checkAssertions()`
