### PR TITLE
Fix getSchemaValidRanges schema query

### LINKED ISSUE #52: getSchemaValidRanges fail after schema check algorithm was improved
Some test fail with https://github.com/ckeditor/ckeditor5-engine/pull/733.

### LINKED ISSUE #2875: getSchemaValidRanges fail after schema check algorithm was improved
Some test fail with https://github.com/ckeditor/ckeditor5-engine/pull/733.

### PR DESCRIPTION
**Pull request by Reinmar**
Fixes ckeditor/ckeditor5#2875. Requires https://github.com/ckeditor/ckeditor5-engine/pull/733.

I also fixed one more test which fails after https://github.com/ckeditor/ckeditor5-engine/pull/733.

### CODE REVIEW

File: src/command/helpers/getschemavalidranges.js [hunk 1]
```diff
@@ -32,8 +33,9 @@ export default function getSchemaValidRanges( attribute, ranges, schema ) {
 
 		while ( !step.done ) {
 			const name = step.value.item.name || '$text';
+			const itemPosition = Position.createBefore( step.value.item );
 
-			if ( !schema.check( { name: name, inside: last, attributes: attribute } ) ) {
+			if ( !schema.check( { name: name, inside: itemPosition, attributes: attribute } ) ) {
```
Comment (scofalik) [inline src/command/helpers/getschemavalidranges.js:38]: With this change maybe we can pass `ignoreElementEnd: true` to `TreeWalker` options?

File: tests/command/helpers/getschemavalidranges.js [hunk 2]
```diff
@@ -21,21 +22,52 @@ describe( 'getSchemaValidRanges', () => {
...
+		schema.allow( { name: 'img', attributes: 'bold', inside: 'p' } );
+		schema.allow( { name: '$text', inside: 'img' } );
+
+		setData( document, '<p>foo<img>xxx</img>bar</p>' );
+
+		const validRanges = getSchemaValidRanges( attribute, ranges, schema );
+		const sel = new Selection();
+		sel.setRanges( validRanges );
+
+		expect( stringify( root, sel ) ).to.equal( '[<p>foo<img>]xxx[</img>bar</p>]' );
```
Comment (scofalik) [inline tests/command/helpers/getschemavalidranges.js:55]: I wonder what would happen if we fire `batch.setAttribute()` on a range like `[</img>bar]` or even `[</img>]`. It should not change the `img`.

On one hand, the second range seems weird, on the other hand it kinda makes perfect sense...

File: tests/command/helpers/getschemavalidranges.js [hunk 3]
```diff
@@ -21,21 +22,52 @@ describe( 'getSchemaValidRanges', () => {
...
 	} );
 
+	it( 'should return unmodified ranges when attribute is allowed on each item (v2 – text is allowed in img)', () => {
+		schema.allow( { name: 'img', attributes: 'bold', inside: 'p' } );
+		schema.allow( { name: '$text', inside: 'img' } );
+
+		expect( getSchemaValidRanges( attribute, ranges, schema ) ).to.deep.equal( ranges );
+	} );
+
+	it( 'should return two ranges when attribute is not allowed in one item', () => {
```
Comment (scofalik) [inline tests/command/helpers/getschemavalidranges.js]: I think the name is wrong - it should be "when attribute is allowed on all items but not on a child in item" or smth like that.

Comment (scofalik) [reply tests/command/helpers/getschemavalidranges.js]: Okay, there is "**in** one item" (not on). Please change to inside and it will be fine.

File: src/command/helpers/getschemavalidranges.js (hunk 1 above)
Comment (scofalik) [reply src/command/helpers/getschemavalidranges.js:38]: Okay I checked it and this proposal is bad. NVM.

File: tests/command/helpers/getschemavalidranges.js (hunk 2 above)
Comment (Reinmar) [reply tests/command/helpers/getschemavalidranges.js:55]: I think that nothing's gonna happen because such a range has two empty flat ranges. And the first range contains `[bar]` and `[]</img>`, so I presume it will only affect the text. Still, we'd need to check this...


EDIT: I started checking it and I realised that attr op can be applied to non-flat ranges. Later on the writer uses `range.getItems()`, though, which ignores element ends, so it seems that I was right anyway.

File: tests/command/helpers/getschemavalidranges.js (hunk 3 above)
Comment (Reinmar) [reply tests/command/helpers/getschemavalidranges.js]: It should be "on", because it's not allowed on that "xxx" text.
